/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Zip.ReadZip;
import com.bulenkov.darcula.DarculaLaf;
import java.awt.event.*;
import java.io.*;
import java.net.URISyntaxException;
import java.util.Scanner;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Kevin
 */
public class Interface extends javax.swing.JFrame {

        FileFilter filter;

        /**
         * Creates new form Interface
         */
        public Interface() {
                initComponents();
                popUpMenu();
                fileFilter();
                setLocationRelativeTo(null);
                setVisible(true);
        }

        private void popUpMenu() {
                JMenu temp = (JMenu) menu.getComponent(0);
                JMenuItem item1 = new JMenuItem("Extract           ");
                item1.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent ae) {
                                fChooser.showOpenDialog(null);
                        }
                });
                temp.add(item1);
        }

        private void fileFilter() {
                filter = new FileFilter() {
                        @Override
                        public boolean accept(File file) {
                                if (file.isDirectory()) {
                                        return true;
                                }
                                String temp = file.getAbsolutePath();
                                return !(!temp.endsWith(".7z") && !temp.endsWith(".zip") && !temp.endsWith(".rar") && !temp.endsWith(".jar"));
                        }

                        @Override
                        public String getDescription() {
                                return "Compressed types (extensions=>   .7z   .zip   .rar .jar)";
                        }
                };
                fChooser.setFileFilter(filter);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                fChooser = new javax.swing.JFileChooser();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtArea = new javax.swing.JTextArea();
                menu = new javax.swing.JMenuBar();
                jMenu1 = new javax.swing.JMenu();
                jMenu2 = new javax.swing.JMenu();

                fChooser.setAcceptAllFileFilterUsed(false);
                fChooser.setApproveButtonText("Extract");
                fChooser.setApproveButtonToolTipText("Extract the chosen file");
                fChooser.setCurrentDirectory(new java.io.File("C:\\Users\\Kevin\\Desktop"));
                fChooser.setDialogTitle("Choose File to Extract");
                fChooser.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                fChooserActionPerformed(evt);
                        }
                });

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                txtArea.setEditable(false);
                txtArea.setColumns(20);
                txtArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
                txtArea.setRows(5);
                jScrollPane1.setViewportView(txtArea);

                jMenu1.setText("File");
                menu.add(jMenu1);

                jMenu2.setText("Edit");
                menu.add(jMenu2);

                setJMenuBar(menu);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void fChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fChooserActionPerformed
                if (!fChooser.isShowing()) {
                        String temp = fChooser.getSelectedFile().getAbsolutePath();
                        ReadZip reader = new ReadZip();
                        try {
                                ProcessBuilder builder = reader.setEverythingAndExtract(temp);
                                Process process = builder.start();
                                Scanner stdInput = new Scanner(process.getInputStream());
                                txtArea.setText("Extraction Starting\n\n\n");
                                while (stdInput.hasNext()) {
                                        txtArea.append(stdInput.nextLine()+"\n");
                                }
                                txtArea.append("\n\n\nExtraction Complete");
                        } catch (IOException | URISyntaxException ioe) {
                        }
                }
        }//GEN-LAST:event_fChooserActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        UIManager.setLookAndFeel(new DarculaLaf());
                } catch (UnsupportedLookAndFeelException ex) {
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> {
                        Interface start = new Interface();
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JFileChooser fChooser;
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenu jMenu2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JMenuBar menu;
        private javax.swing.JTextArea txtArea;
        // End of variables declaration//GEN-END:variables
}
